import { AnimalProfile, Lang } from './types';

export const ANIMALS: AnimalProfile[] = [
  // 动物
  { name_cn: '老虎', name_en: 'Tiger', emoji: '🐯' },
  { name_cn: '熊猫', name_en: 'Panda', emoji: '🐼' },
  { name_cn: '狮子', name_en: 'Lion', emoji: '🦁' },
  { name_cn: '兔子', name_en: 'Rabbit', emoji: '🐰' },
  { name_cn: '狐狸', name_en: 'Fox', emoji: '🦊' },
  { name_cn: '考拉', name_en: 'Koala', emoji: '🐨' },
  { name_cn: '企鹅', name_en: 'Penguin', emoji: '🐧' },
  { name_cn: '猴子', name_en: 'Monkey', emoji: '🐵' },
  { name_cn: '小猪', name_en: 'Piglet', emoji: '🐷' },
  { name_cn: '青蛙', name_en: 'Frog', emoji: '🐸' },
  // 水果
  { name_cn: '苹果', name_en: 'Apple', emoji: '🍎' },
  { name_cn: '香蕉', name_en: 'Banana', emoji: '🍌' },
  { name_cn: '葡萄', name_en: 'Grape', emoji: '🍇' },
  { name_cn: '橙子', name_en: 'Orange', emoji: '🍊' },
  { name_cn: '草莓', name_en: 'Strawberry', emoji: '🍓' },
  { name_cn: '桃子', name_en: 'Peach', emoji: '🍑' },
  { name_cn: '西瓜', name_en: 'Watermelon', emoji: '🍉' },
  { name_cn: '梨', name_en: 'Pear', emoji: '🍐' },
  { name_cn: '猕猴桃', name_en: 'Kiwi', emoji: '🥝' },
  { name_cn: '樱桃', name_en: 'Cherry', emoji: '🍒' },
  { name_cn: '芒果', name_en: 'Mango', emoji: '🥭' },
  { name_cn: '菠萝', name_en: 'Pineapple', emoji: '🍍' },
  // 蔬菜
  { name_cn: '胡萝卜', name_en: 'Carrot', emoji: '🥕' },
  { name_cn: '西兰花', name_en: 'Broccoli', emoji: '🥦' },
  { name_cn: '黄瓜', name_en: 'Cucumber', emoji: '🥒' },
  { name_cn: '生菜', name_en: 'Lettuce', emoji: '🥬' },
  { name_cn: '番茄', name_en: 'Tomato', emoji: '🍅' },
  { name_cn: '土豆', name_en: 'Potato', emoji: '🥔' },
  { name_cn: '洋葱', name_en: 'Onion', emoji: '🧅' },
  { name_cn: '甜椒', name_en: 'Bell Pepper', emoji: '🫑' },
  { name_cn: '辣椒', name_en: 'Pepper', emoji: '🌶️' },
  { name_cn: '牛油果', name_en: 'Avocado', emoji: '🥑' },
  { name_cn: '蘑菇', name_en: 'Mushroom', emoji: '🍄' },
  { name_cn: '玉米', name_en: 'Corn', emoji: '🌽' },
];

export const TEXT = {
  [Lang.CN]: {
    createRoom: '创建房间',
    enterRoom: '进入房间',
    roomCodePlaceholder: '输入房间码加入房间',
    scanQr: '扫码进入',
    room: '房间',
    endGame: '结束房间',
    leaveRoom: '离开房间',
    you: '我',
    transferScore: '转分给',
    confirm: '确认',
    cancel: '取消',
    scoreResult: '最终战绩',
    backHome: '返回首页',
    amount: '数额',
    selfClickToast: '这是你自己 👋',
    mockProcessing: '处理中...',
    roomQrTitle: '房间二维码',
    scanToJoin: '扫码加入房间',
  },
  [Lang.EN]: {
    createRoom: 'Create Room',
    enterRoom: 'Enter Room',
    roomCodePlaceholder: 'Enter room code to join',
    scanQr: 'Scan QR',
    room: 'Room',
    endGame: 'End Room',
    leaveRoom: 'Leave Room',
    you: 'You',
    transferScore: 'Transfer to',
    confirm: 'Confirm',
    cancel: 'Cancel',
    scoreResult: 'Final Results',
    backHome: 'Back to Home',
    amount: 'Amount',
    selfClickToast: "That's you! 👋",
    mockProcessing: 'Processing...',
    roomQrTitle: 'Room QR Code',
    scanToJoin: 'Scan to join room',
  },
};
